apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: hpa-rolebinding
  namespace: default
subjects:
- kind: ServiceAccount
  name: default
  namespace: webhook
roleRef:
  kind: Role
  name: hpa-role
  apiGroup: rbac.authorization.k8s.io
