apiVersion: v1
kind: Service
metadata:
  name: hpa-demo-deployment
  labels:
    run: hpa-demo-deployment
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30007  # Specify a NodePort
  selector:
    run: hpa-demo-deployment
