apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: admission-webhook
  labels:
    app: webhook
    service: admission-webhook
webhooks:
  - name: admission-webhook.webhook.com
    clientConfig:
      # url: "https://admission-webhook.webhook.svc.cluster.local/mutate-replica-count"
      service:
        name: admission-webhook
        namespace: webhook
        path: "/mutate-replica-count"
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tDQpNSUlFQURDQ0F1aWdBd0lCQWdJVVFyOUpIVkJrRitTaUl1VnhGcngyOVplUVNvSXdEUVlKS29aSWh2Y05BUUVMDQpCUUF3VlRFTE1Ba0dBMVVFQmhNQ1NVNHhEekFOQmdOVkJBZ01Ca3RsY21Gc1lURU9NQXdHQTFVRUJ3d0ZTMjlqDQphR2t4RURBT0JnTlZCQW9NQjNWemRDNWpiMjB4RXpBUkJnTlZCQU1NQ25kbFltaHZiMnRmWTJFd0lCY05NalF3DQpOVEkwTVRFek1URTVXaGdQTWpJNU9EQXpNRGt4TVRNeE1UbGFNRlV4Q3pBSkJnTlZCQVlUQWtsT01ROHdEUVlEDQpWUVFJREFaTFpYSmhiR0V4RGpBTUJnTlZCQWNNQlV0dlkyaHBNUkF3RGdZRFZRUUtEQWQxYzNRdVkyOXRNUk13DQpFUVlEVlFRRERBcDNaV0pvYjI5clgyTmhNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDDQpBUUVBdllOaFVxODllN3JiMFdTMGl1cktFNHl5MWZIV0ExbnYzNGhBK0JQN1V4S3owdkh2c2VvLzRsaHg2YVhyDQpuQTgvL3BBTWcya1RNRlQ4UFN4cTNvWmlGNUtGS2g0TnBmRzBQQ3ZGVDByRnI1RmJPZWIrbmdWbVh3aHVaMGlnDQpiTFFhSlMyQmFxRS9rQThtMnhScGIrbU4wKzA4TXZJZHI1VW5CR1BmQ0x2YVJoQXk5cDJZZmw0WFZOOTRGbU1TDQpWcWNWVkQ2b1gwbTNtZ0NPeHpENWhBOTZySXJISWdIT0lYTDdsREtEOElzVHgwUk5TVjZoZmlFTVFQcXhaZFNaDQppU01oSXJKemw3Z3FPTzFmQ016Sit0dlNmQnF3V3IySEdydjJxVVYvd3J1a0NTSmVxbWRBQzdtcWZTVjB5Q2E3DQpuanIyV29lM3ZMeGFtRTFOUVZuZTIrTU4rUUlEQVFBQm80SEZNSUhDTUIwR0ExVWREZ1FXQkJTQnVza2h1dnc5DQpsazQvNFp3WGU2N2Fhbk0yM0RDQmtnWURWUjBqQklHS01JR0hnQlNCdXNraHV2dzlsazQvNFp3WGU2N2Fhbk0yDQozS0ZacEZjd1ZURUxNQWtHQTFVRUJoTUNTVTR4RHpBTkJnTlZCQWdNQmt0bGNtRnNZVEVPTUF3R0ExVUVCd3dGDQpTMjlqYUdreEVEQU9CZ05WQkFvTUIzVnpkQzVqYjIweEV6QVJCZ05WQkFNTUNuZGxZbWh2YjJ0ZlkyR0NGRUsvDQpTUjFRWkJma29pTGxjUmE4ZHZXWGtFcUNNQXdHQTFVZEV3UUZNQU1CQWY4d0RRWUpLb1pJaHZjTkFRRUxCUUFEDQpnZ0VCQUQ0NS9BZDB4YlZGVFFoY3o5STVhN2dQOERFZ3pCUTJwaFZZemxVTGVIN2tFTk5rclR1OTRaeGljRXV5DQpNR3dOcFNYZjd5clB4SEhZK1ltUnN6SmF5YXgwVkMyZEJMK3NyN0N2Um95TlBJSXhaY3VjSU9oRlhXVzYvNHFmDQpuY3p1eTVYUGM4MVhQdmUrQTVwcFV6L3NDa2ZUTDlGMGtUTWlxUGcvR242TUgzdXRIUmpRZktYMUNBUEdGUzVuDQpRY1BtdHB6SWVoa0paVFFjRGd1RHpDSHVIWFBKM09LeDBzb2Rhd1JqdTBiU2R2SThPQW1PT1RFY0FlclJHMEJaDQordU9VelhQM004MytIMEtMLzVTYzVJdW81UmF2TjF2NVY3Z3lSRlBoTkR6MGhLV1J3UitUZ00ybHc0RzQrd0d6DQpENjVodHpuZ3Vxa3hFQkcvRi92YTNSeFFJRzg9DQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tDQo=
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: ["apps"]
        apiVersions: ["v1"]
        resources: ["deployments"]
    sideEffects: None
    admissionReviewVersions: ["v1", "v1beta1"]

