apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: admission-webhook
  labels:
    app: webhook
    service: admission-webhook
webhooks:
  - name: admission-webhook.webhook.com
    clientConfig:
      # url: "https://admission-webhook.webhook.svc.cluster.local/inject-init-container"
      service:
        name: admission-webhook
        namespace: webhook
        path: "/inject-init-container"
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVEekNDQXZlZ0F3SUJBZ0lVT2pnMnVKY1oyalY1T25NOTIrcTNxWUMrUGFNd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1dqRUxNQWtHQTFVRUJoTUNTVTR4RHpBTkJnTlZCQWdNQmt0bGNtRnNZVEVPTUF3R0ExVUVCd3dGUzI5agphR2t4RlRBVEJnTlZCQW9NREVkaGJXRmpiMjF0TG1OdmJURVRNQkVHQTFVRUF3d0tkMlZpYUc5dmExOWpZVEFnCkZ3MHlNREE1TXpBeE5EQTVNek5hR0E4eU1qazBNRGN4TmpFME1Ea3pNMW93V2pFTE1Ba0dBMVVFQmhNQ1NVNHgKRHpBTkJnTlZCQWdNQmt0bGNtRnNZVEVPTUF3R0ExVUVCd3dGUzI5amFHa3hGVEFUQmdOVkJBb01ERWRoYldGagpiMjF0TG1OdmJURVRNQkVHQTFVRUF3d0tkMlZpYUc5dmExOWpZVENDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFECmdnRVBBRENDQVFvQ2dnRUJBTUhjeERub0J2Q2w0YjVYS20vSi8vOVY2TGxZWnJRMzViRWp4OFg4UnJSMFJzOTIKQjVQY0g2YUVUUWNreC9xMEg5ZHdJZGQvMTNzY0hsQXY0K1FaZk1YclF3V3doVVVIaDZyQVpna255d3Bpd2cyVApNZkx5RnNhVmpSZnFUdm1USE5hWVh3M1BJNVliSXBaMjVKUTVZQ3h6WGlJM3FMY1BhVDlpSWMxZXlKVWNMYnNiClBuNXp1NDdoQ3o4VkFPbFBYZGU4OWl6bkoyWU9CZ0ozTnA1RnRwbzFSWFBzY1NoR05zODFtQ1VrR2pkM0doSmwKMHNaNnU0bENTdVBPbHdZVFFNdXQ4STV2QVRJSUVMMTUzTTlIMnZwdnF5M3FNODVUaEhOaitybk5pQ3hUUkY5TwpjWnZqcU93STBhUWVXU0FvajZ5NFZYbXV6TkpFVkN6ZmpVUmxoU01DQXdFQUFhT0J5akNCeHpBZEJnTlZIUTRFCkZnUVVVSzdMYng2RnMrS01Pd1hQNDVvU1pGcjlIQnN3Z1pjR0ExVWRJd1NCanpDQmpJQVVVSzdMYng2RnMrS00KT3dYUDQ1b1NaRnI5SEJ1aFhxUmNNRm94Q3pBSkJnTlZCQVlUQWtsT01ROHdEUVlEVlFRSURBWkxaWEpoYkdFeApEakFNQmdOVkJBY01CVXR2WTJocE1SVXdFd1lEVlFRS0RBeEhZVzFoWTI5dGJTNWpiMjB4RXpBUkJnTlZCQU1NCkNuZGxZbWh2YjJ0ZlkyR0NGRG80TnJpWEdkbzFlVHB6UGR2cXQ2bUF2ajJqTUF3R0ExVWRFd1FGTUFNQkFmOHcKRFFZSktvWklodmNOQVFFTEJRQURnZ0VCQUlOSVV0TG9XWEUwNWdseDBid1l5cGFIcEgrRGxvVjlXdm5wWVlyNgpkSnR1eVFLdXU3S0RGb2tTNE5PYzNnYXp1bkh0c3liV014eG9BdTJBb3BiS3g0bUdBbEVNS2JtWmZlQXZGY3E3ClNUenJHMDdNNmtFOEx0VUVrV3pnUkpCSHI2UElhbjNOOVZPQmhWY0pLQXRIK1pKdTdFMHBJeGlKb3F3eUhXOHIKN3hRakI3bFZlSjJQZ0JJYTFWRi80YUI4bDBtNXUrbjBsdW1IMnVGWE5iQ2ZmcGUxenVHR0ZKM2YvM0FidC9USAo3d0xVRjNpZ25ROHZsRUxyT0lpdjY2Y0RENm83eElXRm5uYVBQRVM5RktkWnpHMEFxYlpoNEVVTHRLMEhtK3hzCmhTQUtKblVLS3dtcnZvYyttUlV5Z0NwRDJqMCtNWHoyVHd3OEFzU1JESWw1UFlZPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    rules:
      - operations: [ "CREATE" ]
        apiGroups: ["*"]
        apiVersions: ["v1"]
        resources: ["pods"]
    sideEffects: None
    admissionReviewVersions: ["v1", "v1beta1"]

